"use client";

import React, { useEffect, useMemo, useState } from "react";
import { listShiftReports, type ShiftReport } from "@/lib/api/oee";

function fmtPct(v: number) {
  return `${Math.round(v * 100)}%`;
}

export default function ReportingPage() {
  const [reports, setReports] = useState<ShiftReport[]>([]);
  const [selected, setSelected] = useState<string>("");

  useEffect(() => {
    listShiftReports().then((r) => {
      setReports(r);
      setSelected(r[0]?.id ?? "");
    });
  }, []);

  const report = useMemo(() => reports.find((r) => r.id === selected), [reports, selected]);

  return (
    <main>
      <header className="page-header">
        <div>
          <div className="h1">Reporting</div>
          <div className="subtle">
            Shift handover reports and KPI breakdowns (generated by backend; UI scaffold).
          </div>
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <button className="btn btn-ghost" onClick={() => listShiftReports().then(setReports)}>
            Refresh
          </button>
          <button className="btn btn-primary" onClick={() => window.print()}>
            Export / Print
          </button>
        </div>
      </header>

      <section className="grid-2">
        <div className="card">
          <div className="card-pad">
            <div style={{ fontWeight: 800 }}>Available reports</div>
            <div className="subtle">Select a shift to view the handover summary.</div>
          </div>
          <div className="card-pad" style={{ display: "grid", gap: 10 }}>
            {reports.map((r) => (
              <button
                key={r.id}
                className="btn"
                onClick={() => setSelected(r.id)}
                style={{
                  justifyContent: "space-between",
                  border: `1px solid ${
                    selected === r.id ? "rgba(37,99,235,0.45)" : "var(--color-border)"
                  }`,
                  background: selected === r.id ? "rgba(37,99,235,0.10)" : "transparent",
                }}
              >
                <span style={{ display: "grid", textAlign: "left", gap: 2 }}>
                  <span style={{ fontWeight: 800 }}>
                    {r.lineName} — {r.shiftName}
                  </span>
                  <span className="subtle">
                    {new Date(r.from).toLocaleString()} → {new Date(r.to).toLocaleString()}
                  </span>
                </span>
                <span className="badge" style={{ borderColor: "rgba(37,99,235,0.25)" }}>
                  <span className="badge-dot" style={{ background: "var(--color-primary)" }} />
                  OEE {fmtPct(r.kpis.oee)}
                </span>
              </button>
            ))}
            {reports.length === 0 ? (
              <div className="subtle">No reports yet.</div>
            ) : null}
          </div>
        </div>

        <div className="card">
          <div className="card-pad">
            <div style={{ fontWeight: 800 }}>Shift handover</div>
            <div className="subtle">Structured summary for operators and supervisors.</div>
          </div>
          <div className="card-pad" style={{ display: "grid", gap: 12 }}>
            {!report ? (
              <div className="subtle">Select a report.</div>
            ) : (
              <>
                <div className="grid-3">
                  <Kpi label="OEE" value={report.kpis.oee} emphasize />
                  <Kpi label="Availability" value={report.kpis.availability} />
                  <Kpi label="Performance" value={report.kpis.performance} />
                  <Kpi label="Quality" value={report.kpis.quality} />
                </div>

                <div className="card card-pad" style={{ background: "rgba(249,250,251,0.6)" }}>
                  <div style={{ fontWeight: 800, marginBottom: 6 }}>Summary</div>
                  <div className="subtle" style={{ color: "var(--color-text)" }}>
                    {report.summary}
                  </div>
                </div>

                <div className="card card-pad">
                  <div style={{ fontWeight: 800, marginBottom: 10 }}>KPI breakdown</div>
                  <table className="table" aria-label="KPI breakdown table">
                    <thead>
                      <tr>
                        <th>Metric</th>
                        <th>Value</th>
                        <th>Notes</th>
                      </tr>
                    </thead>
                    <tbody>
                      <Row metric="Availability" value={report.kpis.availability} note="Downtime impact and changeovers." />
                      <Row metric="Performance" value={report.kpis.performance} note="Speed losses vs ideal cycle." />
                      <Row metric="Quality" value={report.kpis.quality} note="Scrap and rework rate." />
                    </tbody>
                  </table>
                </div>
              </>
            )}
          </div>
        </div>
      </section>
    </main>
  );
}

function Kpi({ label, value, emphasize }: { label: string; value: number; emphasize?: boolean }) {
  return (
    <div className="card card-pad">
      <div className="kpi-label">{label}</div>
      <div className="kpi-value" style={{ color: emphasize ? "var(--color-primary)" : undefined }}>
        {fmtPct(value)}
      </div>
      <div className="progress" aria-hidden="true">
        <div style={{ width: `${Math.max(0, Math.min(1, value)) * 100}%` }} />
      </div>
    </div>
  );
}

function Row({ metric, value, note }: { metric: string; value: number; note: string }) {
  return (
    <tr>
      <td style={{ fontWeight: 750 }}>{metric}</td>
      <td>{fmtPct(value)}</td>
      <td className="subtle" style={{ color: "var(--color-text)" }}>
        {note}
      </td>
    </tr>
  );
}
